### PR TITLE
Support using a :default data reader function

### PR DESCRIPTION
**Pull request by anthonygalea**

### CODE REVIEW

**Comment by anthonygalea** [comment]
Addressed with https://github.com/borkdude/edamame/pull/64

**Comment by borkdude** [comment]
@anthonygalea How does #64 address passing a `:default`?

**Comment by borkdude** [comment]
Oh I see, if you pass a function you can check for `:default`. Maybe we should also support the map case?

**Comment by anthonygalea** [comment]
Yes @borkdude Thanks for your help with this.

**Pull request closed without merging**
